CLASSES = {
    100: "Alive Vegetation",
    110: "Undisturbed Forest",
    120: "Revegetation",
    121: "With Trees (after clear cut)",
    122: "Canopy closing (after thinning/defoliation)",
    123: "Without Trees (shrubs and grasses, no reforestation visible)",
    200: "Disturbed",
    210: "Planned",
    211: "Clear Cut",
    212: "Thinning",
    213: "Forestry Mulching (Non Forest Vegetation Removal)",
    220: "Salvage",
    221: "After Biotic Disturbance",
    222: "After Abiotic Disturbance",
    230: "Biotic",
    231: "Bark Beetle (with decline)",
    232: "Gypsy Moth (temporary)",
    240: "Abiotic",
    241: "Drought",
    242: "Wildfire",
    243: "Wind",
    244: "Avalanche",
    245: "Flood",
}
